// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateReaderRequest defines model for CreateReaderRequest.
type CreateReaderRequest struct {
	Email    openapi_types.Email `json:"email"`
	FullName string              `json:"full_name"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// Reader defines model for Reader.
type Reader struct {
	CreatedAt time.Time           `json:"created_at"`
	Email     openapi_types.Email `json:"email"`
	FullName  string              `json:"full_name"`
	Id        openapi_types.UUID  `json:"id"`
	IsActive  bool                `json:"is_active"`
	UpdatedAt time.Time           `json:"updated_at"`
}

// ReaderID defines model for ReaderID.
type ReaderID = openapi_types.UUID

// CreateReaderJSONRequestBody defines body for CreateReader for application/json ContentType.
type CreateReaderJSONRequestBody = CreateReaderRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CreateReader Create reader
	// (POST /api/v1/readers)
	CreateReader(w http.ResponseWriter, r *http.Request)
	// DeactivateReader Deactivate reader
	// (DELETE /api/v1/readers/{id})
	DeactivateReader(w http.ResponseWriter, r *http.Request, id ReaderID)
	// GetReaderByID Get reader by ID
	// (GET /api/v1/readers/{id})
	GetReaderByID(w http.ResponseWriter, r *http.Request, id ReaderID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// CreateReader Create reader
// (POST /api/v1/readers)
func (_ Unimplemented) CreateReader(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeactivateReader Deactivate reader
// (DELETE /api/v1/readers/{id})
func (_ Unimplemented) DeactivateReader(w http.ResponseWriter, r *http.Request, id ReaderID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetReaderByID Get reader by ID
// (GET /api/v1/readers/{id})
func (_ Unimplemented) GetReaderByID(w http.ResponseWriter, r *http.Request, id ReaderID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateReader operation middleware
func (siw *ServerInterfaceWrapper) CreateReader(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateReader(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeactivateReader operation middleware
func (siw *ServerInterfaceWrapper) DeactivateReader(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ReaderID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeactivateReader(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReaderByID operation middleware
func (siw *ServerInterfaceWrapper) GetReaderByID(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ReaderID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReaderByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/readers", wrapper.CreateReader)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/readers/{id}", wrapper.DeactivateReader)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/readers/{id}", wrapper.GetReaderByID)
	})

	return r
}

type CreateReaderRequestObject struct {
	Body *CreateReaderJSONRequestBody
}

type CreateReaderResponseObject interface {
	VisitCreateReaderResponse(w http.ResponseWriter) error
}

type CreateReader201JSONResponse Reader

func (response CreateReader201JSONResponse) VisitCreateReaderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateReader400JSONResponse ErrorResponse

func (response CreateReader400JSONResponse) VisitCreateReaderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateReader409JSONResponse ErrorResponse

func (response CreateReader409JSONResponse) VisitCreateReaderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateReader500JSONResponse ErrorResponse

func (response CreateReader500JSONResponse) VisitCreateReaderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeactivateReaderRequestObject struct {
	Id ReaderID `json:"id"`
}

type DeactivateReaderResponseObject interface {
	VisitDeactivateReaderResponse(w http.ResponseWriter) error
}

type DeactivateReader204Response struct {
}

func (response DeactivateReader204Response) VisitDeactivateReaderResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeactivateReader400JSONResponse ErrorResponse

func (response DeactivateReader400JSONResponse) VisitDeactivateReaderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeactivateReader404JSONResponse ErrorResponse

func (response DeactivateReader404JSONResponse) VisitDeactivateReaderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeactivateReader500JSONResponse ErrorResponse

func (response DeactivateReader500JSONResponse) VisitDeactivateReaderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetReaderByIDRequestObject struct {
	Id ReaderID `json:"id"`
}

type GetReaderByIDResponseObject interface {
	VisitGetReaderByIDResponse(w http.ResponseWriter) error
}

type GetReaderByID200JSONResponse Reader

func (response GetReaderByID200JSONResponse) VisitGetReaderByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReaderByID400JSONResponse ErrorResponse

func (response GetReaderByID400JSONResponse) VisitGetReaderByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetReaderByID404JSONResponse ErrorResponse

func (response GetReaderByID404JSONResponse) VisitGetReaderByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetReaderByID500JSONResponse ErrorResponse

func (response GetReaderByID500JSONResponse) VisitGetReaderByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// CreateReader Create reader
	// (POST /api/v1/readers)
	CreateReader(ctx context.Context, request CreateReaderRequestObject) (CreateReaderResponseObject, error)
	// DeactivateReader Deactivate reader
	// (DELETE /api/v1/readers/{id})
	DeactivateReader(ctx context.Context, request DeactivateReaderRequestObject) (DeactivateReaderResponseObject, error)
	// GetReaderByID Get reader by ID
	// (GET /api/v1/readers/{id})
	GetReaderByID(ctx context.Context, request GetReaderByIDRequestObject) (GetReaderByIDResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateReader operation middleware
func (sh *strictHandler) CreateReader(w http.ResponseWriter, r *http.Request) {
	var request CreateReaderRequestObject

	var body CreateReaderJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateReader(ctx, request.(CreateReaderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateReader")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateReaderResponseObject); ok {
		if err := validResponse.VisitCreateReaderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeactivateReader operation middleware
func (sh *strictHandler) DeactivateReader(w http.ResponseWriter, r *http.Request, id ReaderID) {
	var request DeactivateReaderRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeactivateReader(ctx, request.(DeactivateReaderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeactivateReader")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeactivateReaderResponseObject); ok {
		if err := validResponse.VisitDeactivateReaderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReaderByID operation middleware
func (sh *strictHandler) GetReaderByID(w http.ResponseWriter, r *http.Request, id ReaderID) {
	var request GetReaderByIDRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReaderByID(ctx, request.(GetReaderByIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReaderByID")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReaderByIDResponseObject); ok {
		if err := validResponse.VisitGetReaderByIDResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FZPb6M+EP0q1vx+RzYk/XNYbu1mVUXqocq1qioHD4krsF17yBZFfPeVDUmh0GgrVdke9gb+M/PmzXsD",
	"O0h1YbRCRQ6SHRhueYGENrwtkQu0i7l/FuhSKw1JrSBpd5gUqEhmEi1EIP2G4bSBCBQvEBKQAiKw+FxK",
	"iwISsiVG4NINFtzHzLQtOEECZRlOUmX8LUdWqjXUdb0/HND8sMgJm8xLfC7RkV/mQkiPiud3Vhu0JNFB",
	"kvHcYQSms7QDLLjMe4mblQgK/nKLak0bSM4uLyMopNq/nw9wRZCVef7Y1Lg7dnc2rKnLx30nUNRieThc",
	"0asnTMmn+2mttkt0RiuHH63Z3/UPx4E0x8aSN4QHcfQCp6Ed4pFTj1HBCb+RDBUNeHu/AccpHuxK8Qf6",
	"iUC6R56S3HaDrLTOkSu/XRrxwRLesBayDnvYTRx1ieqlHJLtw0uV6aHfru4WLNOW5XJlua1YwRVfY4HK",
	"xyRJuQ9z225e3S0ggi1a11yeTaaTqa9XG1TcSEjgfDKdnEMU7Bq6GXMj4+0stqHbzSzQjcF807nHsRCQ",
	"9FzYmhsdXWtRBVFoRR6U16gxuUzDxfjJeSC7jvX/t5hBAv/Fr/Mnbr0ejxm97lPvJ0lYaDwR8J5NZ58G",
	"oa0vZB2dfK5MU3TO975ibYc9xRfT6aeB6Nt+BMtCbXkuBbN7knz+76fL33LxS9KG0UY6FuTPeO5VVDF8",
	"kY6cR3V5WlYIreI5c2i3aFkz2sLHpCwKbquDipndy5j42nlDL1v5P/jjbzwR76SoG2vmSDi0xhyD5/v2",
	"6An04t0vaU9P4hDob2oq4FrMGwQXJ1eV0sQyXSrxJQX02utjIopgjSMz9AapOXNdLeZDlUxPN8YOBP/T",
	"2NfT2A3SnqJVxYJSxiTW/We/H4f1eiQ+/NPXD3Vd/w4AAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
