services:
  postgres:
    image: postgres:17
    container_name: library-postgres

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - library_postgres_data:/var/lib/postgresql/data

volumes:
  library_postgres_data: